export const products = [
    {
      id: '1',
      name: 'Elegance Tote',
      price: 299.99,
      image: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80',
      category: 'Tote Bags',
      description: 'Spacious and elegant tote bag perfect for everyday use. Made from premium leather.',
      features: ['Premium leather', 'Gold-plated hardware', 'Adjustable shoulder strap', 'Interior pockets'],
      colors: ['Black', 'Brown', 'Tan'],
      inStock: true,
    },
    {
      id: '2',
      name: 'Metropolitan Crossbody',
      price: 189.99,
      image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1957&q=80',
      category: 'Crossbody Bags',
      description: 'Compact yet spacious crossbody bag for the modern woman on the go.',
      features: ['Adjustable strap', 'Multiple compartments', 'Secure zip closure', 'Lightweight design'],
      colors: ['Black', 'Red', 'Navy'],
      inStock: true,
    },
    {
      id: '3',
      name: 'Evening Clutch',
      price: 129.99,
      image: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1971&q=80',
      category: 'Clutches',
      description: 'Elegant clutch perfect for special occasions and evening events.',
      features: ['Crystal embellishments', 'Removable chain strap', 'Magnetic closure', 'Satin interior'],
      colors: ['Gold', 'Silver', 'Rose Gold'],
      inStock: true,
    },
    {
      id: '4',
      name: 'Weekender Duffel',
      price: 349.99,
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80',
      category: 'Travel Bags',
      description: 'Spacious duffel bag for weekend getaways and short trips.',
      features: ['Durable canvas', 'Padded shoulder strap', 'Shoe compartment', 'Luggage sleeve'],
      colors: ['Olive', 'Navy', 'Black'],
      inStock: true,
    },
    {
      id: '5',
      name: 'Mini Backpack',
      price: 159.99,
      image: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1975&q=80',
      category: 'Backpacks',
      description: 'Trendy mini backpack combining style with functionality.',
      features: ['Adjustable straps', 'Laptop sleeve', 'Front zip pocket', 'Water-resistant'],
      colors: ['Pink', 'Black', 'Beige'],
      inStock: true,
    },
    {
      id: '6',
      name: 'Satchel Classic',
      price: 249.99,
      image: 'https://images.unsplash.com/photo-1584917865442-89e86c0b6f1b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1935&q=80',
      category: 'Satchels',
      description: 'Timeless satchel that adds sophistication to any outfit.',
      features: ['Top handle', 'Removable shoulder strap', 'Organized interior', 'Signature lining'],
      colors: ['Brown', 'Black', 'Burgundy'],
      inStock: true,
    },
  ];
  
  export const categories = [
    { name: 'All', count: products.length },
    { name: 'Tote Bags', count: products.filter(p => p.category === 'Tote Bags').length },
    { name: 'Crossbody Bags', count: products.filter(p => p.category === 'Crossbody Bags').length },
    { name: 'Clutches', count: products.filter(p => p.category === 'Clutches').length },
    { name: 'Travel Bags', count: products.filter(p => p.category === 'Travel Bags').length },
    { name: 'Backpacks', count: products.filter(p => p.category === 'Backpacks').length },
    { name: 'Satchels', count: products.filter(p => p.category === 'Satchels').length },
  ];